[build-system]
requires = ["setuptools>=61.0", 'tomli;python_version<"3.11"']
build-backend = "setuptools.build_meta"

[project]
name = "medforj"
version = "1.0.0"
description = "MedForj: An open, large-scale foundational generative prior for high-resolution 3D brain MRI"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "Apache-2.0"}
authors = [
    {name = "JH-MIPC", email = "jhmipc@jh.edu"},
]
urls = { "Homepage" = "https://github.com/piksl-research/medforj" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "einops",
    "hd-bet",
    "huggingface_hub",
    "monai @ git+https://github.com/blakedewey/MONAI@f16_stability_diffusion",
    "nibabel",
    "numpy",
    "radifox-utils",
    "safetensors",
    "scipy",
    "tqdm",
    "torch>=2.0.0",
]

[tool.setuptools.packages.find]
include = ["medforj"]
